### ISSUE TITLE
页边距不对，页眉页脚的位置也不对，与word模板不一样。预答辩被老师指出来了，仔细对比了一下，确实比word模板的小，大佬能否改进一下。

### ISSUE THREAD

**Issue by Maxchengqin** [GUET-TeX-Users-Group/GUET_Thesis_LaTeX#13]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by YanMing-lxb** [comment]
非常高兴你能够使用这个模板😊也很高兴能够收到你的反馈，但是在修改这个问题之前，我需要了解一些信息以便能够顺利的改进，还请谅解！

需要了解：
1. 下方页边距太小指的是硕博的还是本科的？
2. 封面还是所有的页边距？
3. 能否方便做一个示意图或者带标注的截图什么的辅助说明？
4. word模板能发给我一份吗？因为我已经毕业，论文模板获取不到，所以需要你发给我一下。

**Comment by Maxchengqin** [comment]
非常感谢你的回复，


1，四边的页边距都比word模板要小，是硕博模板。我昨天自己尝试修改了一下GUET-Thesis.cls文件里关于页边距的设置。发现，即便按照word模板中的参数(上3.0cm，下2.0cm，左3cm，右2.5cm)设置，最终展现出来的效果也比word模板小，甚为不解。另外，我觉的学校的word模板把作用页边距设置为3cm和2.5cm是不合理的，他们可能是出于密封的考虑，把其中一边留多一点，但那样应该奇偶页分别设置才对。
2，封面没注意，后面从摘要开始，页边距都比word模板小。
3，截了一张对比图，放在附件里了，左边为word模板的效果，右边为latex模板的效果。可以看出上下页边距的差异。
4，word模板放在附件里了。




程钦
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GUET-TeX-Users-Group/GUET_Thesis_LaTeX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月15日(星期天) 下午3:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GUET-TeX-Users-Group/GUET_Thesis_LaTeX] 页边距不对，页眉页脚的位置也不对，与word模板不一样。预答辩被老师指出来了，仔细对比了一下，确实比word模板的小，大佬能否改进一下。 (Issue #13)





 
非常高兴你能够使用这个模板😊也很高兴能够收到你的反馈，但是在修改这个问题之前，我需要了解一些信息以便能够顺利的改进，还请谅解！
 
需要了解：
  
下方页边距太小指的是硕博的还是本科的？
 
封面还是所有的页边距？
 
能否方便做一个示意图或者带标注的截图什么的辅助说明？
 
word模板能发给我一份吗？因为我已经毕业，论文模板获取不到，所以需要你发给我一下。

**Comment by YanMing-lxb** [comment]
你好，这头看不到附件，你能把图片放到文字中吗？或者在github中回复我，不要在邮件中回复我，github上无法看到您从邮件中发送的附件！
![image](https://github.com/GUET-TeX-Users-Group/GUET_Thesis_LaTeX/assets/113030089/cff7230c-1f43-4f2e-8dd2-49f2d022552f)

**Comment by Maxchengqin** [comment]
是否方便加个qq。我qq是2655629522
&nbsp;


程钦
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月16日(星期一) 上午9:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GUET-TeX-Users-Group/GUET_Thesis_LaTeX] 页边距不对，页眉页脚的位置也不对，与word模板不一样。预答辩被老师指出来了，仔细对比了一下，确实比word模板的小，大佬能否改进一下。 (Issue #13)





 
你好，这头看不到附件，你能把图片放到文字中吗？或者在github中回复我，不要在邮件中回复我，github上无法看到您从邮件中发送的附件！

**Comment by YanMing-lxb** [comment]
另外关于页边距，模板中是这样设置的
```latex
\ifOptionPrintVersion % 根据eversion/pversion 选项设置页边距
  \geometry{inner=3cm, outer=2cm, top=3cm, bottom=2cm} % bindingoffset为内边距加长2.5cm
\else
  \geometry{left=2.5cm, right=2.5cm, top=3cm, bottom=2cm}
\fi
```
打印版是符合学位论文要求的：上3.0cm，下2.0cm，左3cm，右2.5cm，其中左3cm在该模板中是内侧3cm，这符合实际密封的需求，而电子版则是两侧页边距皆为2.5cm

**Comment by YanMing-lxb** [comment]
已根据需求完成改进。
